S3/poc/s3web/config/routes.rb
Rails.application.routes.draw do
  get '/sso' => "sso#verify"

  root 'buckets#index'

  resources :buckets do
    resources :objects
  end

end

S3/poc/s3web/app/controllers/objects_controller.rb
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

require 'mixlib/shellout'
require 'tmpdir'

class ObjectsController < ApplicationController
  def index  # Display all objects
    @objects = []
    @bucket_name = params[:bucket_id]
    # @objects.push({"title" => "Object_name_1"})
    puts "s3cmd ls #{@bucket_name}  --recursive"
    s3cmd = Mixlib::ShellOut.new("s3cmd ls s3://#{@bucket_name}  --recursive --access_key=#{session[:access_key]} --secret_key=#{session[:secret_key]} --access_token=#{session[:access_token]}")
    s3cmd.run_command
    @objects = []
    s3cmd.stdout.lines do |line|
      case line
      when /^\s*DIR\s+(s3:\/\/.*)$/
        @objects.push({type: :commonprefix, title: $2})
      when /^(.*)\s+(\d+)\s+s3:\/\/([^\/]+)\/(.*)$/
        @objects.push({type: :content,  lastmodified: $1, objectsize: $2, bucketname: $3, objectname: $4})
      end
    end
  end

  def create  # Handler the POST (create)
    @bucket_name = params[:bucket_id]
    @object_name = params[:object][:title]

    uploaded_io = params[:object][:s3object]
    upload_file_path = Rails.root.join('public', 'uploads', @object_name)

    File.open(upload_file_path, 'wb') do |file|
      file.write(uploaded_io.read)
    end

    s3cmd = Mixlib::ShellOut.new("s3cmd put #{upload_file_path} s3://#{@bucket_name}/#{@object_name} --access_key=#{session[:access_key]} --secret_key=#{session[:secret_key]} --access_token=#{session[:access_token]}")
    s3cmd.run_command
    redirect_to bucket_objects_path
    # render plain: "s3cmd put #{uploaded_temp_io_path} s3://#{@bucket_name}/#{@object_name}"
  end

  def show
    @bucket_name = params[:bucket_id]
    @object_name = params[:id]
    @object_name += ".#{params[:format]}" if params[:format]
    Rails.logger.info("@object_name = " + @object_name)

    @object = {}
    if params[:method] == 'delete'
      destroy
    else
      # Show treated as Download.
      @object[:bucketname] = @bucket_name
      @object[:objectname] = @object_name

      # Dir.mktmpdir do |current_tmp_dir|
      #   s3cmd = Mixlib::ShellOut.new("s3cmd get s3://#{@bucket_name}/#{@object_name} --access_key=#{session[:access_key]} --secret_key=#{session[:secret_key]} --access_token=#{session[:access_token]}", :cwd => current_tmp_dir)
      #   s3cmd.run_command
      #   send_file "#{current_tmp_dir}/#{@object_name}", :disposition => 'attachment'
      # end

      current_tmp_dir = Dir.tmpdir()

      s3cmd = Mixlib::ShellOut.new("s3cmd get s3://#{@bucket_name}/#{@object_name} --access_key=#{session[:access_key]} --secret_key=#{session[:secret_key]} --access_token=#{session[:access_token]}", :cwd => current_tmp_dir)
      s3cmd.run_command

      filename = File.join(current_tmp_dir, @object_name)
      file = File.open(filename, "rb")
      contents = file.read
      file.close

      File.delete(filename) if File.exist?(filename)

      send_data(contents, :filename => @object_name, :disposition => 'attachment')

      # s3cmd = Mixlib::ShellOut.new("curl -I http://s3.seagate.com/#{@bucket_name}/#{@object_name}")
      # s3cmd.run_command
      # s3cmd.stdout.lines do |line|
      #   case line
      #   when /^Last-Modified:\s*(.*)$/
      #     @object[:lastmodified] = $1
      #   when /^ETag:\s*(.*)$/
      #     @object[:md5] = $1
      #   end
      # end
      # @object = {"title" => "Object_name_2", "description" => "Second Object", "creation_time" => "4-Oct-2015", "md5sum" => "ABCDKHFL"}
      # render plain: "Displaying Object " + s3cmd.stdout
    end
  end

  def destroy
    s3cmd = Mixlib::ShellOut.new("s3cmd del s3://#{@bucket_name}/#{@object_name} --access_key=#{session[:access_key]} --secret_key=#{session[:secret_key]} --access_token=#{session[:access_token]}")
    s3cmd.run_command
    redirect_to bucket_objects_path
  end
end

S3/poc/s3web/app/helpers/objects_helper.rb
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

module ObjectsHelper
end

S3/poc/s3web/app/views/objects/index.html.erb
<!--
 Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 For any questions about this software or licensing,
 please email opensource@seagate.com or cortx-questions@seagate.com.

-->

<div class="s3-app-container">
  <h1>Listing Objects for /<%= @bucket_name %></h1>
  <%= link_to 'Upload New object', new_bucket_object_path %>
  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th>Object Size (bytes)</th>
      <th>Last Modified</th>
      <th colspan="3"></th>
    </tr>

    <% @objects.each do |object| %>
      <tr>
        <td><%= object[:objectname] %></td>
        <td><%= object[:objectsize] %></td>
        <td><%= object[:lastmodified] %></td>
        <td><%= link_to 'Download', controller: "objects", action: "show", id: object[:objectname] %></td>
        <td><%= link_to 'Delete', controller: "objects", action: "destroy", id: "#{object[:objectname]}", method: :delete, :remote => true %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'Back', buckets_path %>

S3/poc/s3web/app/views/objects/new.html.erb
<!--
 Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 For any questions about this software or licensing,
 please email opensource@seagate.com or cortx-questions@seagate.com.

-->

<h1 class="text-center">Upload Object</h1>

<script>
  $(function() {
    $("input[type=file]").on('change',function(){
     $('#object_title').val(this.files[0].name);
     $('#object_title').tooltip('show');
     $('#object_title').focus();
     setTimeout(function () {
      $('#object_title').tooltip('hide');
    }, 1000);
    });
  });
 </script>

<%= form_for :object, url: bucket_objects_path, :class => 'form-horizontal' do |f| %>
  <p>
    <%= f.label 'Name', :class => "text-info" %>
    <%= f.text_field :title, {"data-toggle" => "tooltip", "data-animation" => "true",  "data-placement" => "right", "title" => "Custom Object Name if required."} %>
  </p>

  <%= f.file_field :s3object %>
</br>
  <p>
    <%= f.submit 'Upload Object', :class => 'btn btn-primary btn-xs' %>
  </p>
<% end %>

<%= link_to 'Back', bucket_objects_path %>

S3/poc/s3web/app/views/objects/show.html.erb
<!--
 Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 For any questions about this software or licensing,
 please email opensource@seagate.com or cortx-questions@seagate.com.

-->

<p>
  <strong>Object Name:</strong>
  <%= @object[:objectname] %>
</p>

<p>
  <strong>Bucket Name:</strong>
  <%= @object[:bucketname] %>
</p>

<p>
  <strong>Last-Modified:</strong>
  <%= @object[:lastmodified] %>
</p>

<p>
  <strong>MD5:</strong>
  <%= @object[:md5] %>
</p>

<%= link_to 'Back', bucket_objects_path %>